// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuiULV_A0FR2ooU7tSWZ4csmlmuu3FMtU',
    appId: '1:830555547016:web:e843b6a5be71fb1fe4463d',
    messagingSenderId: '830555547016',
    projectId: 'cr-dev-portfolio',
    authDomain: 'cr-dev-portfolio.firebaseapp.com',
    storageBucket: 'cr-dev-portfolio.appspot.com',
    measurementId: 'G-NHBHYC1L2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJ6A2tpXX_ajTNhwpzlXxiQFd3T-Ybik',
    appId: '1:830555547016:android:3e837d859af5e418e4463d',
    messagingSenderId: '830555547016',
    projectId: 'cr-dev-portfolio',
    storageBucket: 'cr-dev-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW9YAy8b7G4J9BTzuBnAB6IWtuf5a3mrs',
    appId: '1:830555547016:ios:907900ae0212e47fe4463d',
    messagingSenderId: '830555547016',
    projectId: 'cr-dev-portfolio',
    storageBucket: 'cr-dev-portfolio.appspot.com',
    iosClientId: '830555547016-kteafeuso014th2kg4f9lko5nkdfleuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW9YAy8b7G4J9BTzuBnAB6IWtuf5a3mrs',
    appId: '1:830555547016:ios:907900ae0212e47fe4463d',
    messagingSenderId: '830555547016',
    projectId: 'cr-dev-portfolio',
    storageBucket: 'cr-dev-portfolio.appspot.com',
    iosClientId: '830555547016-kteafeuso014th2kg4f9lko5nkdfleuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPortfolio',
  );
}
